index:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]






voiture_index:
    path: /voitures
    controller: App\Controller\VoitureController::index
    methods: [GET]

voiture_new:
    path: /voiture/new
    controller: App\Controller\VoitureController::new
    methods: [GET, POST]

voiture_show:
    path: /voiture/{id}
    controller: App\Controller\VoitureController::show
    methods: [GET]

voiture_edit:
    path: /voiture/{id}/edit
    controller: App\Controller\VoitureController::edit
    methods: [GET, POST]

voiture_delete:
    path: /voiture/{id}/delete
    controller: App\Controller\VoitureController::delete
   


course_index:
    path: /courses
    controller: App\Controller\CourseController::index
    methods: [GET]


   

course_show:
    path: /course/{id}
    controller: App\Controller\CourseController::show
    methods: [GET]



course_delete:
    path: /course/{id}/delete
    controller: App\Controller\CourseController::delete
   






courseUser_index:
    path: /user/courses
    controller: 'App\Controller\CourseUserController::index'
    methods: ['GET']

courseUser_new:
    path: /user/course/new
    controller: 'App\Controller\CourseUserController::new'
    methods: ['GET', 'POST']

courseUser_show:
    path: /user/course/{id}
    controller: 'App\Controller\CourseUserController::show'
    methods: ['GET']
    requirements:
        id: '\d+'

courseUser_edit:
    path: /user/course/{id}/edit
    controller: 'App\Controller\CourseUserController::edit'
    methods: ['GET', 'POST']
    requirements:
        id: '\d+'

courseUser_delete:
    path: /user/course/{id}/delete
    controller: 'App\Controller\CourseUserController::delete'
 

courseUser_delete2:
    path: /user/course/{id}/delete2
    controller: 'App\Controller\CourseUserController::delete2'

courseUser_avant:
    path: /user/courses/avant
    controller: App\Controller\CourseUserController::coursesAvantDateSysteme
    methods: ['GET']

courseUser_apres:
    path: /user/courses/apres
    controller: App\Controller\CourseUserController::coursesApresOuEgaleDateSysteme
    methods: ['GET']

home:
    path: /home
    controller: App\Controller\HomeController::index
    methods: ['GET']




app_chauffeur_index:
    path: /chauffeur
    controller: 'App\Controller\ChauffeurController::index'
    methods: ['GET']

app_chauffeur_new:
    path: /chauffeur/new
    controller: 'App\Controller\ChauffeurController::new'
    methods: ['GET', 'POST']

app_chauffeur_show:
    path: /chauffeur/{id}
    controller: 'App\Controller\ChauffeurController::show'
    methods: ['GET']
    requirements:
        id: '\d+'

app_chauffeur_edit:
    path: /chauffeur/{id}/edit
    controller: 'App\Controller\ChauffeurController::edit'
    methods: ['GET', 'POST']
    requirements:
        id: '\d+'

app_chauffeur_delete:
    path: /chauffeur/{id}/delete
    controller: 'App\Controller\ChauffeurController::delete'
   
  # config/routes.yaml

app_postule_index:
    path: /postule
    controller: 'App\Controller\PostuleController::index'
    methods: ['GET']

app_postule_new:
    path: /postule/new
    controller: 'App\Controller\PostuleController::new'
    methods: ['GET', 'POST']

app_postule_show:
    path: /postule/{id}
    controller: 'App\Controller\PostuleController::show'
    methods: ['GET']

afficher:
    path: /postuleAfficher/{id}
    controller: 'App\Controller\PostuleController::afficher'
    methods: ['GET']

app_postule_edit:
    path: /postule/{id}/edit
    controller: 'App\Controller\PostuleController::edit'
    methods: ['GET', 'POST']

app_postule_delete:
    path: /postule/{id}/delete
    controller: 'App\Controller\PostuleController::delete'

app_postule_delete2:
    path: /postule/{id}/supprimer
    controller: 'App\Controller\PostuleController::delete2'
